name: CD - Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🐳 Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🚀 Construir e push da imagem Docker
        run: |
          docker build -t meuusuario/priorify-backend .
          docker tag meuusuario/priorify-backend meuusuario/priorify-backend:latest
          docker push meuusuario/priorify-backend:latest
        working-directory: backend

      - name: 📦 SSH e atualizar o servidor (opcional)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull meuusuario/priorify-backend:latest
            docker stop priorify-backend || true
            docker rm priorify-backend || true
            docker run -d --name priorify-backend -p 4000:4000 meuusuario/priorify-backend:latest
