name: CI/CD - Deploy no Render

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🛠️ Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install
        working-directory: backend

      - name: 🔍 Rodar ESLint para validar código
        run: npm run lint
        working-directory: backend

      - name: ✅ Rodar testes automatizados
        run: npm run test
        working-directory: backend

      - name: 🔄 Build do Backend
        run: npm run build
        working-directory: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # ⚠️ Só executa se "build-and-test" for bem-sucedido

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🚀 Deploy para o Render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
